name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake 4.x
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~4.2.0"

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: build/Release/wperf.exe
          generate_release_notes: true
